name: master-cicd
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: code checkout
          uses: actions/checkout@v4 
        - name: copying some content
          run: echo "master cicd,python,terraform and kubernetes kumar" > kumar_target.sh
        - name: upload artifact to be available in other jobs
          uses: actions/upload-artifact@v4.4.3
          with:
            name: kumars_aim
            path: kumar_target.txt
    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: download the artifact
              uses: actions/download-artifact@v4.4.3
              with:
                name: kumars_aim
            - name: list and check files
              run: |
                ls -ltra
                grep -i python "kumar_target.sh"
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: download the artifact
              uses: actions/download-artifact@v4.4.3
              with:
                name: kumars_aim
            - name: print content of the file
              run: cat kumar_target.sh
